### ISSUE TITLE
No access to homebridge nor UI

### ISSUE THREAD

**Issue by splifter** [oznu/docker-homebridge#143]
Hi,

i've followed the wiki to install homebridge on my raspberry-pi via docker-compose.
The issue i'm facing now is, that neither the iOS "Home" app nor via the webui i've access to the homebridge.

My docker-compose file: https://pastebin.com/AXYhBQJj
The log file (I've removed the QR-code): https://pastebin.com/WZsWntAQ

What am i doing wrong?
Thanks for support and the great work!

**Comment by oznu** [comment]
Hi @splifter,

The docker-compose.yml file does not show you having host networking enabled. This is required.

```
version: '2'
services:
  homebridge:
    image: oznu/homebridge:raspberry-pi
    restart: always
    network_mode: host
    volumes:
      - ./config:/homebridge
    environment:
      - PGID=1000
      - PUID=1000
      - HOMEBRIDGE_CONFIG_UI=1
      - HOMEBRIDGE_CONFIG_UI_PORT=8080
```
