### ISSUE TITLE
"Couldn't add accessory"

### ISSUE THREAD

**Issue by koraysels** [oznu/docker-homebridge#152]
I setup everything correctly but my phone won't add the bridge after I scanned the QR code. Even when i type the code manually it wont work.

**Comment by koraysels** [comment]
I was oon a raspberry pi model 3 

fixed it by using a different docker image. My docker-compose.yml file now looks like this: 

```
version: '2'
services:
  homebridge:
    image: oznu/homebridge:no-avahi-raspberry-pi
    restart: always
    network_mode: host
    volumes:
      - ./config:/homebridge
    environment:
      - PGID=1000
      - PUID=1000
      - HOMEBRIDGE_CONFIG_UI=1
      - HOMEBRIDGE_CONFIG_UI_PORT=8080
```
