### ISSUE TITLE
file owner changes to uid or gid

### ISSUE THREAD

**Issue by kappes** [oznu/docker-homebridge#18]
I have the strange issue that the file owner:group of the mounted files is changing on the host to 911, which is the uid and gid I have set in the env.

##### docker-compose
``` yml
  homebridge:
    image: oznu/homebridge:raspberry-pi
    restart: always
    network_mode: host
    environment:
      - TZ=Europe/Vienna
      - PGID=911
      - PUID=911
    volumes:
      - /home/pirate/docker-libertas/homebridge:/homebridge
```

##### bash
``` bash
drwxr-xr-x 5    911    911 4096 Jul 20 19:24 homebridge
```

It is doing this continuously. I've change the permissions while the container was running and after some time it changed just back.
