### ISSUE TITLE
1 hour difference between system time and Homebridge time

### ISSUE THREAD

**Issue by JacVid** [oznu/docker-homebridge#181]
Hello,

since i'm using Hombridge on my RaspberryPi using Raspbian, I can't adjust the correct time of the Homebridge log.

I still have 1 hour delay between the system and Homebridge, as you can see with an example of log:

> ...
> homebridge_1  | [2/16/2019, 5:01:43 PM] Homebridge is running on port 51826.
> homebridge_1  | [2/16/2019, 5:01:49 PM] [Hue] Lumière: set homekit status fault from 0 to 1
> pi@RaspberryPi:~/homebridge $ date
> samedi 16 février 2019, 18:01:56 (UTC+0100)
> ...

Any idea of what I should change or update ?

Thanks.

**Comment by oznu** [comment]
Hi,

Make sure the `TZ` variable is correct, and the city you have picked isn't subject to a different day light savings schedule:

https://github.com/oznu/docker-homebridge/blob/master/README.md#parameters

**Comment by JacVid** [comment]
Hello,

thanks for your answer.

following your advise, here is the new content of my docker-compose.yml

```
version: '2'
services:
  homebridge:
    image: oznu/homebridge:raspberry-pi
    restart: always
    network_mode: host
    volumes:
      - ./config:/homebridge
    environment:
      - TZ=Europe/Paris
      - PGID=1000
      - PUID=1000
      - HOMEBRIDGE_CONFIG_UI=1
      - HOMEBRIDGE_CONFIG_UI_PORT=8080
```
Unfortunatly, I still have the issue. HomeBridge is not aligned with system. 

System is set at UTC+0100 whereas HomeBridge still at UTC 2019

Raspberry Terminal
```
pi@RaspberryPi:~ $ date
dimanche 17 février 2019, 11:48:39 (UTC+0100)
```

Homebridge Docker Terminal
```
/homebridge # date
Sun Feb 17 10:50:29 UTC 2019
```

Another idea ?

Thanks.
