### ISSUE TITLE
Hang and fail on install wget for debian-raspberry-pi

### ISSUE THREAD

**Issue by drewcovi** [oznu/docker-homebridge#274]
**Describe Your Problem:**

Start stalls when attempting to install wget

**Logs:**

```
homebridge    | Installing extra packages for debian linux:  wget
homebridge    | /usr/lib/apt/methods/http: error while loading shared libraries: libseccomp.so.2: cannot open shared object file: No such file or directory
homebridge    | /usr/lib/apt/methods/http: error while loading shared libraries: libseccomp.so.2: cannot open shared object file: No such file or directory
homebridge    | /usr/lib/apt/methods/http: error while loading shared libraries: libseccomp.so.2: cannot open shared object file: No such file or directory
homebridge    | 
homebridge    | --------------------------------------------------------------
homebridge    | Killed
homebridge    | ERROR INSTALLING CUSTOM PACKAGES
homebridge    | --------------------------------------------------------------
homebridge    | Failed to install custom packages. See log above for details.
homebridge    | Please ensure all packages requested are named correctly.
homebridge    | --------------------------------------------------------------
```

**Docker Start Command:**

```
  homebridge:
    image: oznu/homebridge:debian-raspberry-pi
    restart: always
    network_mode: host
    container_name: homebridge
    volumes:
      - ./homebridge:/homebridge
      - /opt/vc/lib:/opt/vc/lib
      - /usr/lib/arm-linux-gnueabihf:/usr/lib/arm-linux-gnueabihf
    environment:
      - PGID=1000
      - PUID=1000
      - HOMEBRIDGE_CONFIG_UI=1
      - HOMEBRIDGE_CONFIG_UI_PORT=8080
      - HOMEBRIDGE_INSECURE=1
      - PACKAGES=wget
      - LD_LIBRARY_PATH=/opt/vc/lib
      - HOMEBRIDGE_DEBUG=0
    devices:
      - /dev/vchiq:/dev/vchiq
    logging:
      options:
        max-size: '100k'
        max-file: '50'
```

**Environment:**

* **Host Operating System**: Raspbian
* **Docker Version**: Docker version 19.03.4, build 9013bf5
* **Image Tag / Type**: oznu/homebridge:debian-raspberry-pi
