### ISSUE TITLE
homebridge-network-sensor can't execute apr-scan with sudo

### ISSUE THREAD

**Issue by fkloes** [oznu/docker-homebridge#277]
**Describe Your Problem:**

Hey there.
I'm trying to get the [homebridge-network-sensor](https://www.npmjs.com/package/homebridge-network-sensor) plugin running. It uses `arp-scan` to figure out, if an observed device is online. Therefore it executes commands [like](https://github.com/willyzha/homebridge-network-sensor/blob/8c8d69e8899c2eb3745bb1b09f14adbe3713ec6a/index.js#L63) 
```
sudo arp-scan --interface=eth0 -l | grep -i 50:85:33:03:92:A6
```
Since `arp-scan` is not part of the docker image, i've added it by using a custom `Dockerfile` - later i found out, that the `startup.sh` could have also been an option.

From the terminal within `homebridge-config-ui-x` i can execute the command with and without sudo. But when it's executed by the plugin, it doesn't work. I've changed the `index.js` of the plugin a little bit to get some logs, and it seems that there is an issue with sudo (see logs section).

So i've tried to create an alias for sudo within the startup.sh like `alias sudo="sudo -S "`. I've also tried to add the alias to `/etc/profile` with the help of my Dockerfile. Noting worked. 

The only way to make it working without changing the plugin code was to run Homebridge as root by setting `PGID` and `PUDI` to `0`. This would basically fit my requirements now, and i think due to the encapsulation by the container it doesn't cause much risks. But i wonder if there is a more fashionable way.

Best regards.

**Logs:**

```
sudo: a terminal is required to read the password; either use the -S option to read from standard input or configure an askpass helper

 
We trust you have received the usual lecture from the local System
Administrator. It usually boils down to these three things:

    #1) Respect the privacy of others.
    #2) Think before you type.
    #3) With great power comes great responsibility.
```

**Docker Start Command:**

```
version: '2'
services:
  homebridge:
    image: oznu/homebridge:latest
    restart: always
    network_mode: host
    environment:
      - TZ=Europe/Berlin
      - PGID=1000
      - PUID=1000
      - HOMEBRIDGE_CONFIG_UI=1
      - HOMEBRIDGE_CONFIG_UI_PORT=8080
    volumes:
      - ./volumes/homebridge:/homebridge
```

**Environment:**

* **Host Operating System**: Raspbian
* **Docker Version**: Docker version 19.03.6, build 369ce74
* **Image Tag / Type**: latest
