### ISSUE TITLE
Installing custom plugins via -P parameter?

### ISSUE THREAD

**Issue by VirtualWolf** [oznu/docker-homebridge#286]
**Describe Your Problem:**
Forgive me if this is a silly question, but I'm trying to play around with writing my own plugin as per [Plugin Development](https://github.com/homebridge/homebridge#plugin-development) in the main Homebridge README, and I can't work out how I should be doing that via this Docker image! The main reason I want to run this via Docker is to keep everything as self-contained as possible.

**Docker Start Command:**

Starting via `docker-compose up -d`.
```
version: '2'
services:
  homebridge:
    image: oznu/homebridge:raspberry-pi
    restart: always
    network_mode: host
    volumes:
      - ./config:/homebridge
    environment:
      - PGID=1000
      - PUID=1000
      - HOMEBRIDGE_CONFIG_UI=1
      - HOMEBRIDGE_CONFIG_UI_PORT=8080
```

**Environment:**

* **Host Operating System**: Raspbian
* **Docker Version**: 19.03.8, build afacb8b
* **Image Tag / Type**: `oznu/homebridge:raspberry-pi`
