### ISSUE TITLE
Cannot install addons / dont persist after reboot

### ISSUE THREAD

**Issue by vordenken** [oznu/docker-homebridge#314]
**Describe Your Problem:**

I cannot install plugins (or they are gone after restart). I tried it with docker exec CONTAINER_NAME npm install homebridge-hue, with this it gets installed but package.json doesnt get changed.
with startup.sh, it doesnt get installed at all. The following logs are with startup.sh (npm install homebridge-hue)

I can see in the log that the package.json cannot be written to. But why?  
**Logs:**

```
s6-init] making user provided files available at /var/run/s6/etc...exited 0.,
[s6-init] ensuring user provided files have correct perms...exited 0.,
[fix-attrs.d] applying ownership & permissions fixes...,
[fix-attrs.d] done.,
[cont-init.d] executing container initialization scripts...,
[cont-init.d] 10-adduser: executing... ,
,
-------------------------------------,
GID/UID,
-------------------------------------,
User uid:    1001,
User gid:    1001,
-------------------------------------,
,
[cont-init.d] 10-adduser: exited 0.,
[cont-init.d] 20-set-timezone: executing... ,
[cont-init.d] 20-set-timezone: exited 0.,
[cont-init.d] 30-packages: executing... ,
[cont-init.d] 30-packages: exited 0.,
[cont-init.d] 40-dbus-avahi: executing... ,
[cont-init.d] 40-dbus-avahi: exited 0.,
[cont-init.d] 45-user-data: executing... ,
npm WARN saveError EBUSY: resource busy or locked, rename '/homebridge/package.json.2639416830' -> '/homebridge/package.json',
+ homebridge-hue@0.11.71,
updated 1 package and audited 157 packages in 34.191s,
,
29 packages are looking for funding,
  run `npm fund` for details,
,
found 0 vulnerabilities,
,
[cont-init.d] 45-user-data: exited 0.,
[cont-init.d] 50-plugins: executing... ,
,
,
    Thank you for using the oznu/homebridge docker image!,
,
  If you find this project useful please STAR it on GitHub:,
,
         https://github.com/oznu/docker-homebridge,
,
,
Homebridge: Installing plugins...,
removed 87 packages and audited 70 packages in 6.407s,
,
29 packages are looking for funding,
  run `npm fund` for details,
,
found 0 vulnerabilities,
,
```

**Docker Start Command:**

```
version: '3.7'

services:

  app:
    image: oznu/homebridge:no-avahi

    networks:
      - traefik-public

    volumes:
      - homebridge_config:/homebridge
      - ~/docker_swarm/volumes/homebridge/config.json:/homebridge/config.json
      - ~/docker_swarm/volumes/homebridge/package.json:/homebridge/package.json
    environment:
      - PGID=1001
      - PUID=1001
      # Run the homebridge configuration UI
      - HOMEBRIDGE_CONFIG_UI=1
      - HOMEBRIDGE_CONFIG_UI_PORT=8080
    ports:
     - 51826:51826/tcp
     - 52100-52150:52100-52150/tcp
    deploy:
        labels:
          - "traefik.enable=true"
          - "traefik.http.routers.homebridge.rule=Host(`homebridge.MYDOMAIN.COM`)"
          - "traefik.http.routers.homebridge.entrypoints=websecure"
          - "traefik.http.routers.homebridge.tls.certresolver=cloudflare"
          - "traefik.http.services.homebridge.loadbalancer.server.port=8080"
      

networks:
  traefik-public:
    external: true

volumes:
  homebridge_config:
```

**Homebridge Config:**

```json
{
  "bridge": {
    "name": "Homebridge",
    "username": "CC:22:3D:E3:CE:30",
    "port": 51826,
    "pin": "031-45-154"
  }
}



```

**Screenshots:**

**Environment:**

* **Host Operating System**:  Raspian lite latest
* **Docker Version**:  19.03.11
* **Image Tag / Type**:  no-avahi
