### ISSUE TITLE
s6-applyuidgid: fatal: unable to exec hb-service: Exec format error

### ISSUE THREAD

**Issue by bmingles** [oznu/docker-homebridge#315]
**Describe Your Problem:**

I am running docker-compose on a Rasberry PI 3, but am seeing continuous errors in my docker logs

```
s6-applyuidgid: fatal: unable to exec hb-service: Exec format error
```

I installed via the manual install instructions found here:
https://github.com/oznu/docker-homebridge/wiki/Homebridge-on-Raspberry-Pi#manual-install

**Logs:**

This just repeats over and over:
```
...
homebridge       | s6-applyuidgid: fatal: unable to exec hb-service: Exec format error
homebridge       |
homebridge       |
homebridge       |     Thank you for using the oznu/homebridge docker image!
homebridge       |
homebridge       |   If you find this project useful please STAR it on GitHub:
homebridge       |
homebridge       |          https://github.com/oznu/docker-homebridge
...
```

**Docker Start Command:**

```
docker-compose up -d
```

```yaml
version: "3"
services:
    homebridge:
      image: oznu/homebridge:raspberry-pi
      container_name: homebridge
      restart: always
      network_mode: host
      environment:
        - TZ=America/Chicago
        - PGID=1001                 # found using id cmd for my user
        - PUID=1001                 # found using id cmd for my user
        - HOMEBRIDGE_CONFIG_UI=1
        - HOMEBRIDGE_CONFIG_UI_PORT=8080
      volumes:
        - ./homebridge:/homebridge
```

**Homebridge Config:**

```json
{
    "bridge": {
        "name": "Homebridge XXXX",
        "username": "XX:XX:XX:XX:XX:XX",
        "port": #####,
        "pin": "###-##-###"
    },
    "accessories": [],
    "platforms": []
}
```

**Screenshots:**

**Environment:**

* **Host Operating System**: 
Raspbian Buster
* **Docker Version**: 
Docker version 19.03.12, build 48a6621
* **Image Tag / Type**: 
raspberry-pi
