### ISSUE TITLE
Creating multiple homebridge containers on same docker host running different ports and "usernames", adding second bridge on apple device actually adds the first homebridge.

### ISSUE THREAD

**Issue by Numbski** [oznu/docker-homebridge#335]
Bascially as above.

I have a working docker instance with lots of accessessories and platforms.  Works without a hitch.  top of config.js appears like this:

```json
    "bridge": {
        "name": "Homebridge Primary",
        "username": "0E:7C:88:95:97:DA",
        "port": 53525,
        "pin": "031-45-154"
    }
```

Created a second homebridge container, set it up, unique ports for both homebridge and config-ui-x. Everything in config-ui-x seems to work, adding plugins works. 

```json
    "bridge": {
        "name": "Homebridge Family Room DirecTV",
        "username": "0E:FA:3A:A8:39:F7",
        "port": 53792,
        "pin": "031-45-155"
    }
```

 When I go to add the second bridge to my apple device, it actually tries to add the first one, despite using the second bridge's pin.  I get an error about the bridge already existing in Apple Home.  

**Logs:**

No logs attached because so far I haven't identified any logging that would be useful.  It is apparent that the attempt to join apple home is being answered by the wrong container - but what I am missing is *why* that is happening.  The only thing I could think of is quirkiness with multicast DNS, or the fact that I haven't altered /etc/hostname in the image for either container, resulting in both sending mDNS for the same host, but that's a reach.  Avahi is no longer being used for homebridge, so I am at a loss.
```
Show the Docker container logs here
```

**Docker Start Command:**

```
version: '2'
services:
  homebridge:
    image: oznu/homebridge:ubuntu
    restart: always
    network_mode: host
    environment:
      - PGID=1000
      - PUID=1000
      - HOMEBRIDGE_CONFIG_UI=1
      - HOMEBRIDGE_CONFIG_UI_PORT=80
      - TZ=America/Chicago
      - PACKAGES=apcupsd,jq,man,mlocate,mosquitto,netcat,openssh-server,telnet,vim
    volumes:
      - ./volumes/homebridge-primary:/homebridge
      - ./volumes/config:/config
      - ./volumes/scripts:/scripts
  homebridge-dtv:
    image: oznu/homebridge:ubuntu
    restart: always
    network_mode: host
    environment:
      - PGID=1000
      - PUID=1000
      - HOMEBRIDGE_CONFIG_UI=1
      - HOMEBRIDGE_CONFIG_UI_PORT=8080
      - TZ=America/Chicago
      - PACKAGES=jq,man,mlocate,netcat,vim
    volumes:
      - ./volumes/homebridge-dtv:/homebridge


docker-compose up -d
```

**Homebridge Config:**

```json
see above
```

**Screenshots:**

**Environment:**
see above

* **Host Operating System**: Ubuntu Server, LTS (just installed a week ago)
* **Docker Version**: Docker version 19.03.13, build 4484c46d9d
* **Image Tag / Type**: oznu/homebridge:ubuntu
