### ISSUE TITLE
Accessory Not found

### ISSUE THREAD

**Issue by louia** [oznu/docker-homebridge#346]
**Describe Your Problem:**

My iPhone Home App tell me "Accessory Not found" and I don't have the message box "Accessory Not Certified....".

Latest HomeBridge, iOS 14, iPhone 11
**Logs:**

```
Homebridge v1.2.5 is running on port 53044.
```

**Docker Start Command:**

```
version: '2'
services:
  homebridge:
    image: oznu/homebridge:latest
    restart: always
    network_mode: host
    environment:
      - PGID=1000
      - PUID=1000
      - HOMEBRIDGE_CONFIG_UI=1
      - HOMEBRIDGE_CONFIG_UI_PORT=8080
    volumes:
      - ./homebridge:/homebridge
```

**Homebridge Config:**

```json
{
    "bridge": {
        "name": "LouisBridge",
        "username": "0E:D4:3E:21:41:70",
        "port": 53044,
        "pin": "031-45-154"
    },
    "accessories": [
        {
            "accessory": "Plex",
            "name": "Plex",
            "plex_token": "MwuYXAeE8cJcdwKt63sk"
        }
    ],
    "platforms": [
        {
            "name": "Config",
            "port": 8080,
            "platform": "config"
        },
        {
            "units": "ca",
            "interval": 5,
            "stations": [
                {
                    "nameNow": "METEO",
                    "service": "openweathermap",
                    "key": "",
                    "locationCity": "",
                    "language": "fr",
                    "compatibility": "home",
                    "forecast": [
                        "Today"
                    ],
                    "conditionCategory": "simple",
                    "now": true,
                    "extraHumidity": false
                }
            ],
            "platform": "WeatherPlus"
        }
    ]
}
```

**Screenshots:**

**Environment:**

* **Host Operating System**: Pop_Os 20.10
* **Docker Version**: Docker version 19.03.13, build 4484c46d9d
* **Docker Compose Version**: docker-compose version 1.27.4, build 40524192
* **Image Tag / Type**: latest
