### ISSUE TITLE
clean shutdown of HB service with shutdown of docker container

### ISSUE THREAD

**Issue by thecem** [oznu/docker-homebridge#348]
On docker container reboot/ stop/ shutdown there is no gracefully shutdown of HB srervice, the container stops immediately.

I would expect that the HB service would gracefully shutdown on a container stop or reboot or shutdwon:

`docker container stop ----time=30 homebridge`
`docker container kill ----signal=SIGQUIT homebridge`

What is the right SIGTERM ?
Could it be changed that the HB service get the correct shutdown request?:

```
[1/15/2021, 4:52:25 PM] [Homebridge UI] Homebridge restart request received
[1/15/2021, 4:52:25 PM] [Homebridge UI] UI / Bridge settings have not changed; only restarting Homebridge process
[1/15/2021, 4:52:25 PM] [HB Supervisor] Sending SIGTERM to Homebridge
[1/15/2021, 4:52:25 PM] Got SIGTERM, shutting down Homebridge...
[1/15/2021, 4:52:25 PM] [Nuki] closed http://192.168.76.100:43415/notify
[1/15/2021, 4:52:30 PM] [Hue] goodbye
[1/15/2021, 4:52:30 PM] [Nuki] goodbye
[1/15/2021, 4:52:30 PM] [HB Supervisor] Homebridge Process Ended. Code: 143, Signal: null
[1/15/2021, 4:52:35 PM] [HB Supervisor] Restarting Homebridge...
[1/15/2021, 4:52:35 PM] [HB Supervisor] Starting Homebridge with extra flags: -I -P /homebridge/node_modules
[1/15/2021, 4:52:36 PM] [HB Supervisor] Started Homebridge v1.2.5 with PID: 461
[1/15/2021, 4:52:36 PM] Loaded config.json with 2 accessories and 10 platforms.

```
**Logs:**

```
Not relevant because the docker stops the container immediately:


2021-01-15 16:40:03 | container | Container homebridge_homebridge_1 exited with status code 0
-- | -- | --
2021-01-15 16:40:00 | container | Container homebridge_homebridge_1 killed


```

**Docker Start Command:**

```
version: '2'
services:
  homebridge:
    image: oznu/homebridge:latest
    restart: always
    network_mode: host
    environment:
      - PGID=0
      - PUID=0
      - HOMEBRIDGE_CONFIG_UI=1
      - HOMEBRIDGE_CONFIG_UI_PORT=8581
    volumes:
      - /mnt/data/supervisor/homeassistant/homebridge:/homebridge
```

**Homebridge Config:**

```json
Show your homebridge config.json here
```

**Screenshots:**

![grafik](https://user-images.githubusercontent.com/46648579/104747864-4f56fb00-5751-11eb-97c0-b209b9bdae0a.png)

**Environment:**

* **Host Operating System**:  NUC10/Win10/VM/HA/(portainer)/(oznu/docker-homebridge)
* **Docker Version**:  19.03.13
* **Image Tag / Type**:  latest
