### ISSUE TITLE
Request to support running as a non-root user

### ISSUE THREAD

**Issue by branic** [oznu/docker-homebridge#355]
**Describe Your Problem:**

When using a docker-compose file that specifies a user and group the container fails to run and a permission denied error is generated.

I'd like to be able to have the process inside the container not require root to be able to run.

**Logs:**

```
% docker container logs f08cb346b14b
s6-mkdir: warning: unable to mkdir /var/run/s6: Permission denied
s6-mkdir: warning: unable to mkdir /var/run/s6: Permission denied
s6-mkdir: warning: unable to mkdir /var/run/s6: Permission denied
s6-mkdir: warning: unable to mkdir /var/run/s6: Permission denied
s6-mkdir: warning: unable to mkdir /var/run/s6: Permission denied
s6-mkdir: warning: unable to mkdir /var/run/s6: Permission denied
s6-mkdir: warning: unable to mkdir /var/run/s6: Permission denied
s6-mkdir: warning: unable to mkdir /var/run/s6: Permission denied
s6-mkdir: warning: unable to mkdir /var/run/s6: Permission denied
s6-mkdir: warning: unable to mkdir /var/run/s6: Permission denied
s6-mkdir: warning: unable to mkdir /var/run/s6: Permission denied
s6-mkdir: warning: unable to mkdir /var/run/s6: Permission denied
s6-mkdir: warning: unable to mkdir /var/run/s6: Permission denied
```

**Docker Start Command:**

```
version: '2'
services:
  homebridge:
    image: oznu/homebridge:ubuntu
    restart: always
    network_mode: host
    environment:
      - PUID=502
      - PGID=20
      - HOMEBRIDGE_CONFIG_UI=1
      - HOMEBRIDGE_CONFIG_UI_PORT=8581
      - TZ=Canberra/Australia
    volumes:
      - ./homebridge:/homebridge
    user: "502:20"
```

**Homebridge Config:**

None yet as the container won't start

**Screenshots:**

N/A

**Environment:**

* **Host Operating System**:  macOS
* **Docker Version**:  20.10.2, build 2291f61
* **Image Tag / Type**:  ubuntu
