### ISSUE TITLE
Error: forkpty(3) failed. Docker arm

### ISSUE THREAD

**Issue by Casburggraaf** [oznu/docker-homebridge#363]
when i try to install a plugin i get this error:
```
USER: root
DIR: /homebridge
CMD: npm install --save homebridge-hue@latest


Error: forkpty(3) failed.
```
Docker version: Docker version 18.09.9, build 039a7df
Docker compose:
```
homebridge:
    image: oznu/homebridge:ubuntu-arm32v7
    container_name: homebridge
    restart: always
    environment:
      PGID: 101
      HOMEBRIDGE_CONFIG_UI_PORT: 9090
      PUID: 1026
      HOMEBRIDGE_CONFIG_UI: 1
      DSM_HOSTNAME: "HOST"
    hostname: HOST
    network_mode: host
    volumes:
    - /volume1/docker/homebridge:/homebridge
```
Someone got any tips?
