### ISSUE TITLE
forkpty(3) failed on ARMv7 Processor - with any plugin installation

### ISSUE THREAD

**Issue by RedJohn14** [oznu/docker-homebridge#388]
**Describe Your Problem:**
Error if I try to install a plugin. I tested several plugins nothing worked :-( ANY ideas? Thanks !!!
forkpty(3) failed 

**Logs:**
[9/12/2021, 10:41:40 PM] [Homebridge UI] Running Command: npm install --save homebridge-ring@latest
[9/12/2021, 10:41:40 PM] [Homebridge UI] Error: forkpty(3) failed.

**Docker Start Command:**
Here is my compose file:

```
version: '2'
services:
  homebridge:
    image: oznu/homebridge:ubuntu-arm32v7
    restart: always
    network_mode: host
    environment:
      - PGID=1000
      - PUID=1000
      - HOMEBRIDGE_CONFIG_UI=1
      - HOMEBRIDGE_CONFIG_UI_PORT=8581
      - TZ=Australia/Canberra
    volumes:
      - ./volumes/homebridge:/homebridge

```

**Homebridge Config:**

```
{
    "bridge": {
        "name": "Homebridge 344A",
        "username": "0E:38:1C:D7:34:4A",
        "port": 51471,
        "pin": "031-45-154"
    },
    "accessories": [],
    "platforms": [
        {
            "name": "Config",
            "port": 8581,
            "platform": "config"
        }
    ]
}
```

**Environment:**

* **Host Operating System**: Synology NAS with CPU: ARMv7 Processor rev 4 (v7l) - AnnapurnaLabs Alpine (Device Tree)
* **Docker Version**: Docker 19.03.0
* **Image Tag / Type**: oznu/homebridge:ubuntu-arm32v7
