### ISSUE TITLE
Fatal Python error when executing python in the terminal

### ISSUE THREAD

**Issue by lightingghost** [oznu/docker-homebridge#403]
**Describe Your Problem:**
I am trying to install additional python packages with homebridge. But getting the error below when using the internal terminal to run 

```
pip3 install bleak
```

moreover, running `python3` will give the same error output, but `python` and `python3 --version` works as expected.

**Logs:**

```
/homebridge # python3
Python path configuration:
  PYTHONHOME = (not set)
  PYTHONPATH = (not set)
  program name = 'python3'
  isolated = 0
  environment = 1
  user site = 1
  import site = 1
  sys._base_executable = '/usr/bin/python3'
  sys.base_prefix = '/usr'
  sys.base_exec_prefix = '/usr'
  sys.executable = '/usr/bin/python3'
  sys.prefix = '/usr'
  sys.exec_prefix = '/usr'
  sys.path = [
    '/usr/lib/python38.zip',
    '/usr/lib/python3.8',
    '/usr/lib/python3.8/lib-dynload',
  ]
Fatal Python error: init_fs_encoding: failed to get the Python codec of the filesystem encoding
Python runtime state: core initialized
LookupError: unknown encoding: UTF-8

Current thread 0x76f48558 (most recent call first):
<no Python frame>
```

**Docker Start Command:**

```
version: '2'
services:
  homebridge:
    image: oznu/homebridge:raspberry-pi
    restart: always
    network_mode: host
    environment:
      - PGID=1000
      - PUID=1000
      - HOMEBRIDGE_CONFIG_UI=1
      - HOMEBRIDGE_CONFIG_UI_PORT=8581
    volumes:
      - ./volumes/homebridge:/homebridge
```

**Homebridge Config:**

Not related.

**Screenshots:**

**Environment:**

* **Host Operating System**:Raspbian
* **Docker Version**: Docker version 20.10.11, build dea9396
* **Image Tag / Type**: raspberry-pi

Any help will be appreciated.
