### ISSUE TITLE
Rpi4B 64bit Raspbian 11 - problem with ffmpeg (FFmpeg process creation failed: spawn...ENOENT)

### ISSUE THREAD

**Issue by S474N** [oznu/docker-homebridge#408]
**Describe Your Problem:**

No image and stream in Homekit (Home.app). This problem is after switching from 32bit Raspbian to 64bit. Raspbian 11. Same configuration works on another 32bit RPi absolutelly correctly.

**Logs:**

[1/6/2022, 10:08:50 AM] [Camera-ffmpeg] [Cam 14] FFmpeg process creation failed: spawn /homebridge/node_modules/homebridge-camera-ffmpeg/node_modules/ffmpeg-for-homebridge/ffmpeg ENOENT

```
[1/6/2022, 10:08:50 AM] [Camera-ffmpeg] [Cam 14] FFmpeg process creation failed: spawn /homebridge/node_modules/homebridge-camera-ffmpeg/node_modules/ffmpeg-for-homebridge/ffmpeg ENOENT
```

**Docker Start Command:**

```
  homebridge:
    container_name: homebridge
    image: oznu/homebridge:2021-12-12-no-avahi-arm64v8
#    image: oznu/homebridge:no-avahi-arm64v8
    restart: unless-stopped
    environment:
      - TZ=Europe/Prague
      - PGID=1000
      - PUID=1000
      - HOMEBRIDGE_CONFIG_UI=1
      - HOMEBRIDGE_CONFIG_UI_PORT=8581
    volumes:
      - ./volumes/homebridge:/homebridge
    network_mode: host

```

**Homebridge Config:**

```json

            "platform": "Camera-ffmpeg",
            "cameras": [
              {
                    "name": "Cam 14",
                    "manufacturer": "Hikvision",
                    "model": "DS-2CD2785FWD-IZS",
                    "serialNumber": "xxxxxx",
                    "firmwareRevision": "5.6.5",
                    "videoConfig": {
                        "source": "-rtsp_transport tcp -re -i rtsp://user:pass@IP:554/Streaming/Channels/502",
                        "stillImageSource": "-i http://user:pass@IP/ISAPI/ContentMgmt/StreamingProxy/channels/502/picture",
                        "maxStreams": 2,
                        "maxWidth": 1280,
                        "maxHeight": 1024,
                        "maxFPS": 20
                    }
                }
```

**Screenshots:**

**Environment:**

* **Host Operating System**:  Raspbian 11
PRETTY_NAME="Debian GNU/Linux 11 (bullseye)"
NAME="Debian GNU/Linux"
VERSION_ID="11"
VERSION="11 (bullseye)"
VERSION_CODENAME=bullseye
ID=debian

* **Docker Version**:  Docker version 20.10.12, build e91ed57

* **Image Tag / Type**:  tested on images `2021-12-12-no-avahi-arm64v8` and `no-avahi-arm64v8`
