### ISSUE TITLE
help on  **docker build** of an unaltered image from your git repo. What docker flags ...

### ISSUE THREAD

**Issue by grsilver** [oznu/docker-homebridge#411]
**Describe Your Problem:**

Hello, I love this project. It has great value to me.
Can you please kindly help me on  a **docker build** of an unaltered image from your git repo?
What docker flags do you use to build?
Are you using [buildX](https://docs.docker.com/desktop/multi-arch/) for docker multi-cpu cross architecture?

Thank you very much!

WHY? I'm trying to apply Datadog telemetry for monitoring as in here grsilver/[homebridge-docker-datadog](https://github.com/grsilver/homebridge-docker-datadog )

- I AM able to run an image directly pulled from your docker cloud repo 
  - docker-compose up -d
  - docker-compose.yml [screenshot](https://a.cl.ly/GGuE2lqq)
    - ... image: oznu/homebridge:latest
    
- I am ALSO able to a build working image by inheriting from your docker cloud repo image
  - as in shown in the same grsilver/[homebridge-docker-datadog](https://github.com/grsilver/homebridge-docker-datadog )
  - ```docker build -t docker build -t grsilver/homebridge-oznu-b_pi-src_from_oznu:v001 . ```
  -  again ```docker-compose up -d```
  - and it works great in my browser
 
- **BUT I am NOT able to pull from you git** [oznu/docker-homebridge](https://github.com/oznu/docker-homebridge) repo and **build myself**
  - git clone https://github.com/oznu/docker-homebridge.git
  - ```docker build -t docker build -t grsilver/homebridge-oznu-b_pi-src_git:v001 . ```
  -  or 

```
docker buildx  \
 build  \
 --load  \
 --platform linux/arm64 \
 -t  \
 grsilver/homebridge-oznu-b_pi-src_git:v003  \

```

  - no changes to anything else ( except trying to delete Dockerfile and replacing with Dockerfile.ubuntu ) 
  -  ```docker-compose up -d```
  -  in same directory as the other two image runs above
    -  and also in a new directory, which does create the mounted volume ```config``` which maps to ```/homebridge``` but there is nothing in it

```
version: '2'
services:
  homebridge:
    image: grsilver/homebridge-oznu-b_pi-src_git:v002
    # image: grsilver/homebridge-oznu-built_oznu_save_state:v001
    # image: grsilver/homebridge-oznu-b_pi-src_from_oznu:v001
    # image: oznu/homebridge:latest
    # image: oznu/homebridge:ubuntu
    restart: always
    network_mode: host
    container_name: grsilver-homebridge
    platform: linux/arm64/v8
    volumes:
      - ./config:/homebridge
    environment:
      - TZ=America/New_York
      - PGID=1000
      - PUID=1000
      - HOMEBRIDGE_CONFIG_UI=1
      - HOMEBRIDGE_CONFIG_UI_PORT=8581
      - DD_ENV="dev"
      - DD_SERVICE="homebridge-grsilver"
      - DD_VERSION="00.00.001"
```

  - the container runs but the UI is not reachable via a browser.
    - but the web ui isn't working 
    -  http://XX.XXX.XXX.XX:8581 (default port settings) no ping
  - I need to call homebridge manually [screenshot of CLI](https://a.cl.ly/geudopKp)
    - via ```sudo docker exec -it grsilver-homebridge sh``` and calling ```homebridge```
    - it says it is up and running on port  33409
      - but this http://XX.XXX.XXX.XX:33409/ only yields
      - nothing but some JSON ```{"status":-70409}```
      - [screenshot](https://a.cl.ly/Qwu4b4pd)
    - the CLI screen shot also show a notes that it can't find the config file, maybe it's a host directory permissions thing?
  - this is on a **Raspberry Pi with Ubuntu 64 server and docker running**.

 

**Logs:**

```
Having trouble getting them
```

**Docker Start Command:**

```
docker run --net=host ...
```

**Homebridge Config:**

```json
Show your homebridge config.json here
```
NA

**Screenshots:**

**Environment:**

* **Host Operating System**: 
* **Docker Version**: 
* **Image Tag / Type**:
