### ISSUE TITLE
docker swarm changing HOMEBRIDGE_CONFIG_UI_PORT doesn't do anything

### ISSUE THREAD

**Issue by vordenken** [oznu/docker-homebridge#415]
**Describe Your Problem:**

I'm running this docker container on my raspberry pi using docker swarm and a compose file. 
Changing the environment variable HOMEBRIDGE_CONFIG_UI_PORT to another port doesn't change the port. 
The container is still accessible via the standard port 8581. 

**Logs:**

```
    Thank you for using the oznu/homebridge docker image!


  If you find this project useful please STAR it on GitHub:


         https://github.com/oznu/docker-homebridge


                Or donate to the project:


            https://github.com/sponsors/oznu

                  https://paypal.me/oznu


Homebridge: Installing plugins...


up to date in 2s


up to date in 2s

[cont-init.d] 50-plugins: exited 0.

[cont-init.d] 55-config-ui: executing... 

Enabling homebridge-config-ui-x...

[cont-init.d] 55-config-ui: exited 0.

[cont-init.d] done.

[services.d] starting services

Starting cron


  If you find this project useful please STAR it on GitHub:


         https://github.com/oznu/docker-homebridge


                Or donate to the project:


            https://github.com/sponsors/oznu

                  https://paypal.me/oznu


[services.d] done.

[1/27/2022, 11:34:41 AM] [HB Supervisor] Homebridge Storage Path: /homebridge

[1/27/2022, 11:34:41 AM] [HB Supervisor] Homebridge Config Path: /homebridge/config.json

[1/27/2022, 11:34:41 AM] [HB Supervisor] Logging to /homebridge/homebridge.log

[1/27/2022, 11:34:41 AM] [HB Supervisor] OS: Linux 5.10.92-v8+ arm64

[1/27/2022, 11:34:41 AM] [HB Supervisor] Node.js v16.13.2 /usr/local/bin/node

[1/27/2022, 11:34:41 AM] [HB Supervisor] Homebridge Path: /usr/local/lib/node_modules/homebridge/bin/homebridge

[1/27/2022, 11:34:41 AM] [HB Supervisor] UI Path: /usr/local/lib/node_modules/homebridge-config-ui-x/dist/bin/standalone.js

[1/27/2022, 11:34:48 AM] [Homebridge UI] Homebridge Config UI X v4.42.0 is listening on :: port 8581

[1/27/2022, 11:34:48 AM] [HB Supervisor] Starting Homebridge with extra flags: -I -P /homebridge/node_modules

[1/27/2022, 11:34:48 AM] [HB Supervisor] Started Homebridge v1.4.0 with PID: 405

[1/27/2022, 11:34:50 AM] Loaded config.json with 1 accessories and 3 platforms.
```

**Docker Start Command:**

```
version: '3.4'
services:
  app:
    image: oznu/homebridge:latest
    networks:
      - hostnetwork
    environment:
      - PGID=1000
      - PUID=1000
      - HOMEBRIDGE_CONFIG_UI=1
# Standardlogin ist admin:admin
      - HOMEBRIDGE_CONFIG_UI_PORT=84
    volumes:
      - app:/homebridge
networks:
  hostnetwork:
    external:
      name: "host"

volumes:
   app:
```

**Homebridge Config:**

```json
Show your homebridge config.json here
```

**Screenshots:**

**Environment:**

* **Host Operating System**:  Raspberry Pi OS 64bit (Linux raspberrypi 5.10.92-v8+ #1514 SMP PREEMPT Mon Jan 17 17:39:38 GMT 2022 aarch64 GNU/Linux)
* **Docker Version**:  Docker version 20.10.12, build e91ed57
* **Image Tag / Type**:  oznu/homebridge:latest
