### ISSUE TITLE
Instructions on how to use plugin from local source code

### ISSUE THREAD

**Issue by sebbegg** [oznu/docker-homebridge#424]
**Describe Your Problem:**
I'm trying to test a plugin that I have forked and modified locally.
I'd obviously like to include that in the docker image. I'm not totally familiar with npm and especially how that's handled in homebridge with plugins, so I hope this isn't something obvious.

Are there instructions as to what the recommended procedure is?

```dockerfile
FROM oznu/homebridge:latest

ADD . /hmip/  # add local clone of https://github.com/thkl/homebridge-homematic
RUN npm install /hmip && \
    npm list
```
I also played with some alternative dockerfiles using `npm link` or a `npm install -g /hmip`.
In none of my tests I managed to get my modified code running in homebridge.

I'm guessing that maybe the startup procedure that installs plugins overwrites the locally installed version?

**Logs:**

```
Show the Docker container logs here
```

**Docker Start Command:**
I use docker-compose:

```yaml
version: "3"
services:
  homebridge:
    build:
      context: .
    image: my-homebridge:latest
    #image: oznu/homebridge
    command: ["-D", "-I"]
    restart: always
    environment:
      - TZ=Europe/Berlin
      - PGID=1000
      - PUID=1000
      - HOMEBRIDGE_CONFIG_UI=1
      - HOMEBRIDGE_CONFIG_UI_PORT=8080
      - HOMEBRIDGE_DEBUG=1
      - DEBUG=alexa*
    ports:
      - ...
```

**Homebridge Config:**

```json
Show your homebridge config.json here
```

**Screenshots:**

**Environment:**

* **Host Operating System**: 
* **Docker Version**: 
* **Image Tag / Type**: latest

**Comment by riteesh3** [comment]
Hello,

Did you find any solution to run docker with local test plugin for development?

**Comment by sevenc-nanashi** [comment]
For anyone who is looking for solution, I install and use local plugin like this:

- Run `npm pack` in your plugin package
- Create `local_plugins` mount, like this:
```yml
version: '2'
services:
  homebridge:
    build:
      dockerfile: ./image.dockerfile  # I have to install etherwake so I use modified dockerfile
    restart: always
    network_mode: host
    volumes:
      - ./volumes/homebridge:/homebridge
      - ./volumes/local_plugins:/mnt/local_plugins  # <-- This is the important like
      - ./volumes/dotssh:/root/.ssh
    logging:
      driver: json-file
      options:
        max-size: "10mb"
        max-file: "1"
```

- Copy your plugin into the local_plugins:
```bash
chmod +x o+x ./volumes/local_plugins
cp /path/to/your/plugin.tgz ./volumes/local_plugins
```

- Install your plugin in homebridge shell:
```bash
cd /homebridge
npm i /mnt/local_plugins/plugin.tgz
```
