### ISSUE TITLE
homebridge-config-ui-x update - unable to start

### ISSUE THREAD

**Issue by animosity22** [oznu/docker-homebridge#432]
**Describe Your Problem:**
After a reboot, the config-ui-x update seems to cause it to stop working.

**Logs:**

```
Homebridge: Installing plugins...

up to date in 2s

up to date in 2s
[cont-init.d] 50-plugins: exited 0.
[cont-init.d] 55-config-ui: executing...
Enabling homebridge-config-ui-x...
Updating Homebridge Config UI X to latest version; this might take a few minutes...
npm ERR! code ENOTEMPTY
npm ERR! syscall rename
npm ERR! path /usr/local/lib/node_modules/homebridge-config-ui-x
npm ERR! dest /usr/local/lib/node_modules/.homebridge-config-ui-x-3gtnOIj4
npm ERR! errno -39
npm ERR! ENOTEMPTY: directory not empty, rename '/usr/local/lib/node_modules/homebridge-config-ui-x' -> '/usr/local/lib/node_modules/.homebridge-config-ui-x-3gtnOIj4'

npm ERR! A complete log of this run can be found in:
npm ERR!     /root/.npm/_logs/2022-04-21T12_57_39_967Z-debug-0.log
[cont-init.d] 55-config-ui: exited 217.
[cont-init.d] done.
[services.d] starting services
Starting cron

  If you find this project useful please STAR it on GitHub:

         https://github.com/oznu/docker-homebridge

                Or donate to the project:

            https://github.com/sponsors/oznu
                  https://paypal.me/oznu

[services.d] done.
s6-applyuidgid: fatal: unable to exec hb-service: No such file or directory
```

**Docker Start Command:**

```
  homebridge:
   image: oznu/homebridge:ubuntu
   container_name: homebridge
   restart: always
   network_mode: host
   environment:
    - PGID=1000
    - PUID=1000
    - HOMEBRIDGE_CONFIG_UI=1
    - HOMEBRIDGE_CONFIG_UI_PORT=8080
    - HOMEBRIDGE_INSECURE=1
    - TZ=America/New_York
    - QEMU_ARCH=x86_64
    - S6_KEEP_ENV=1
    - ENABLE_AVAHI=0
   volumes:
    - '/data/homebridge:/homebridge'
```

**Homebridge Config:**

```json
Show your homebridge config.json here
```

**Screenshots:**

**Environment:**

* **Host Operating System**: Ubuntu 20.04 LTS
* **Docker Version**:  Version:           20.10.12
* **Image Tag / Type**: ubuntu
