### ISSUE TITLE
Homebridge unable to start after latest update

### ISSUE THREAD

**Issue by pa-friederich** [oznu/docker-homebridge#438]
### Describe The Bug

I upgraded the docker image with the latest one, from a few days ago. The previous version was Homebridge UI v4.44.0 and everything was working fine. Since the update, I am unable to have home bridge running because it encounter the following error:

"../src/util.cc:188:double node::GetCurrentTimeInMicroseconds(): Assertion `(0) == (uv_gettimeofday(&tv))' failed."

I don't have many plugins, mqtttthing, z2m and shelly. There was 2 plugins that were needed to be updated before doing the upgrade, but I did the homebridge update first and nothing is working now.

Is there a way to revert back to the previous image or is this a bug coming from the update ?

### Docker Config

```yml
version: '2'
services:
  homebridge:
    image: oznu/homebridge:latest
    container_name: homebridge
    restart: always
    network_mode: host
    environment:
      - PGID=1000
      - PUID=1000
      - HOMEBRIDGE_CONFIG_UI=1
      - HOMEBRIDGE_CONFIG_UI_PORT=8581
      - TZ=Europe/Zurich
    volumes:
      - $HOME/docker/homebridge/volumes/homebridge:/homebridge
```

### Logs

```text
pi@raspberrypi:~/docker/compose-files/homebridge $ docker-compose logs
Attaching to homebridge
homebridge    | [s6-init] making user provided files available at /var/run/s6/etc...exited 0.
homebridge    | [s6-init] ensuring user provided files have correct perms...exited 0.
homebridge    | [fix-attrs.d] applying ownership & permissions fixes...
homebridge    | [fix-attrs.d] done.
homebridge    | [cont-init.d] executing container initialization scripts...
homebridge    | [cont-init.d] 10-adduser: executing... 
homebridge    | 
homebridge    | -------------------------------------
homebridge    | GID/UID
homebridge    | -------------------------------------
homebridge    | User uid:    1000
homebridge    | User gid:    1000
homebridge    | -------------------------------------
homebridge    | 
homebridge    | [cont-init.d] 10-adduser: exited 0.
homebridge    | [cont-init.d] 20-set-timezone: executing... 
homebridge    | [cont-init.d] 20-set-timezone: exited 0.
homebridge    | [cont-init.d] 30-packages: executing... 
homebridge    | [cont-init.d] 30-packages: exited 0.
homebridge    | [cont-init.d] 40-dbus-avahi: executing... 
homebridge    | [cont-init.d] 40-dbus-avahi: exited 0.
homebridge    | [cont-init.d] 45-user-data: executing... 
homebridge    | [cont-init.d] 45-user-data: exited 0.
homebridge    | [cont-init.d] 50-plugins: executing... 
homebridge    | 
homebridge    | 
homebridge    |     Thank you for using the oznu/homebridge docker image!
homebridge    | 
homebridge    |   If you find this project useful please STAR it on GitHub:
homebridge    | 
homebridge    |          https://github.com/oznu/docker-homebridge
homebridge    | 
homebridge    |                 Or donate to the project:
homebridge    | 
homebridge    |             https://github.com/sponsors/oznu
homebridge    |                   https://paypal.me/oznu
homebridge    | 
homebridge    | Homebridge: Installing plugins...
homebridge    | Node.js[310]: ../src/util.cc:188:double node::GetCurrentTimeInMicroseconds(): Assertion `(0) == (uv_gettimeofday(&tv))' failed.
homebridge    | Aborted (core dumped)
```

### Host Operating System

Raspberry Pi OS / Raspbian

### Host Architecture

armv6l

**Comment by oznu** [comment]
See https://github.com/oznu/docker-homebridge/issues/434#issuecomment-1114930154 - you need to update your host or roll back. You can replace the `latest` tag with the dated release of `2022-04-14`

**Comment by oznu** [comment]
Adding this to your docker-compose might help too:

```
    security_opt: # this option
      - seccomp:unconfined
 ```


```yml
version: '2'
services:
  homebridge:
    image: oznu/homebridge:latest
    container_name: homebridge
    restart: always
    network_mode: host
    security_opt: # this option
      - seccomp:unconfined
    environment:
      - PGID=1000
      - PUID=1000
      - HOMEBRIDGE_CONFIG_UI=1
      - HOMEBRIDGE_CONFIG_UI_PORT=8581
      - TZ=Europe/Zurich
    volumes:
      - $HOME/docker/homebridge/volumes/homebridge:/homebridge
 ```
