### ISSUE TITLE
Container doesn't start

### ISSUE THREAD

**Issue by frkd-dev** [oznu/docker-homebridge#441]
### Describe The Bug

Today I've pulled latest image and started getting crashes in the node.js with immediate container stop.

### Docker Config

```yml
version: "3.3"
services:
  homebridge:
    image: oznu/homebridge:ubuntu
    container_name: homebridge
    restart: always
    network_mode: host
    environment:
      - TZ=Europe/Berlin
      - PGID=1000
      - PUID=1000
    volumes:
      - ${HOME}/.docker-volumes/homebridge:/homebridge
```

### Logs

```text
homebridge    | Starting Avahi daemon
homebridge    | Found user 'avahi' (UID 105) and group 'avahi' (GID 108).
homebridge    | Successfully dropped root privileges.
homebridge    | avahi-daemon 0.7 starting up.
homebridge    | No service file found in /etc/avahi/services.
homebridge    | *** WARNING: Detected another IPv4 mDNS stack running on this host. This makes mDNS unreliable and is thus not recommended. ***
homebridge    | Joining mDNS multicast group on interface docker0.IPv4 with address 172.17.0.1.
homebridge    | New relevant interface docker0.IPv4 for mDNS.
homebridge    | Joining mDNS multicast group on interface eth0.IPv4 with address 10.0.0.59.
homebridge    | New relevant interface eth0.IPv4 for mDNS.
homebridge    | Joining mDNS multicast group on interface lo.IPv4 with address 127.0.0.1.
homebridge    | New relevant interface lo.IPv4 for mDNS.
homebridge    | Network interface enumeration completed.
homebridge    | Registering new address record for 172.17.0.1 on docker0.IPv4.
homebridge    | Registering new address record for fdde:8f13:8403:0:dea6:32ff:fecb:c600 on eth0.*.
homebridge    | Registering new address record for fdde:8f13:8403::9e2 on eth0.*.
homebridge    | Registering new address record for 10.0.0.59 on eth0.IPv4.
homebridge    | Registering new address record for ::1 on lo.*.
homebridge    | Registering new address record for 127.0.0.1 on lo.IPv4.
homebridge    | touch: setting times of '/homebridge/homebridge.log': Operation not permitted
homebridge    | sleep: cannot read realtime clock: Operation not permitted
homebridge    | Node.js[445]: ../src/util.cc:188:double node::GetCurrentTimeInMicroseconds(): Assertion `(0) == (uv_gettimeofday(&tv))' failed.
homebridge    | Aborted (core dumped)
```

### Host Operating System

Raspberry Pi OS / Raspbian

### Host Architecture

armv7l
