### ISSUE TITLE
Node.js error

### ISSUE THREAD

**Issue by krizzziz** [oznu/docker-homebridge#443]
### Describe The Bug

The container with Homebridge is failing to startup. I received a RPI4 and downloaded a Raspan Bullseye (latest image of the website). Installed Docker and Portainer. But now I am getting error messages that has to do something with node.js and now the containers does not startup.

### Docker Config

```yml
version: '2'
services:
  homebridge:
    image: oznu/homebridge:raspberry-pi
    restart: always
    network_mode: host
    volumes:
      - ./config:/homebridge
    environment:
      - PGID=1000
      - PUID=1000
      - HOMEBRIDGE_CONFIG_UI=1
      - HOMEBRIDGE_CONFIG_UI_PORT=8581
```

### Logs

```text
`Node.js[7152]: ../src/util.cc:188:double node::GetCurrentTimeInMicroseconds(): Assertion `(0) == (uv_gettimeofday(&tv))' failed.
Aborted (core dumped)`
```

### Host Operating System

Raspberry Pi OS / Raspbian

### Host Architecture

armv7l
