### ISSUE TITLE
Can't start docker compose after upgrade to 2022-06-02

### ISSUE THREAD

**Issue by hannoeru** [oznu/docker-homebridge#444]
### Describe The Bug

Looks like is some thing related to s6.

### Workaround

Add `privileged: true` to `docker-compose.yml` can fix it.

### Docker Config

```yml
version: '2'
services:
  homebridge:
    image: oznu/homebridge:apt
    restart: always
    network_mode: host
    environment:
      - TZ=Asia/Tokyo
    volumes:
      - ./data:/homebridge
    logging:
      driver: json-file
      options:
        max-size: "10mb"
        max-file: "1"
```

### Logs

```text
homebridge-homebridge-1  | s6-svscan: warning: unable to iopause: Operation not permitted
homebridge-homebridge-1  | s6-svscan: warning: executing into .s6-svscan/crash
homebridge-homebridge-1  | s6-svscan crashed. Killing everything and exiting.
homebridge-homebridge-1  | s6-linux-init-hpr: fatal: unable to reboot(): Operation not permitted
homebridge-homebridge-1 exited with code 111
```

### Host Operating System

Raspberry Pi OS / Raspbian

### Host Architecture

armv7l
