### ISSUE TITLE
Cant deploy the Stack -> Error

### ISSUE THREAD

**Issue by pillemats** [oznu/docker-homebridge#448]
### Current Situation

i am using my Hassio on my 32GB VM image on ESXI and want to install the image with config below.

everytime i want to deploy the stack i get the following error and i dont know how to fix it
<img width="317" alt="Bildschirmfoto 2022-06-07 um 19 48 09" src="https://user-images.githubusercontent.com/26164977/172449565-490407f5-4cf4-497c-856b-9468dff90e99.png">

Hopefully somone can help and explain how to fix

thanks

### Docker Config

```yml
version: '2'
services:
  homebridge:
    image: oznu/homebridge:ubuntu
    restart: always
    network_mode: host
    environment:
      - PGID=1000
      - PUID=1000
      - HOMEBRIDGE_CONFIG_UI=1
      - HOMEBRIDGE_CONFIG_UI_PORT=8581
      - TZ=Europe/Berlin
    volumes:
      - ./volumes/homebridge:/homebridge
```

### Host Operating System

ESXI Base
Hass.io as ESXI Image .ova

### Host Architecture

x86_64 / amd64

i cant realy read the error but maybe it is an problem of the data rights?
how can i change it in vm?
