### ISSUE TITLE
Latest Ubuntu container fails to start due to missing user

### ISSUE THREAD

**Issue by clickbg** [oznu/docker-homebridge#458]
### Describe The Bug

After pulling the latest Ubuntu image (tag: ubuntu) the HB container fails to start

### Docker Config

```yml
homebridge:
    image: oznu/homebridge:ubuntu
    container_name: homebridge
    restart: always
    network_mode: host
    environment:
      - PUID=${PUID}
      - PGID=${PUID}
      - TZ=${TZ}
      - HOMEBRIDGE_CONFIG_UI=1
      - HOMEBRIDGE_CONFIG_UI_HOST=10.168.4.4
      - HOMEBRIDGE_CONFIG_UI_PORT=8581
      - ENABLE_AVAHI=1
    volumes:
      - ${CONFDIR}/homebridge:/homebridge
    healthcheck:
      test: curl --fail http://10.168.4.4:8581 || exit 1
      interval: 10s
      retries: 5
      start_period: 5s
      timeout: 10s
    labels:
      "autoheal": "true"
```

### Logs

```text
s6-rc: info: service credits: starting

    Thank you for using the oznu/homebridge docker image!

  If you find this project useful please STAR it on GitHub:

         https://github.com/oznu/docker-homebridge

                Or donate to the project:

            https://github.com/sponsors/oznu
                  https://paypal.me/oznu

s6-rc: info: service credits successfully started
s6-rc: info: service fix-attrs successfully started
s6-rc: info: service legacy-cont-init: starting
s6-rc: info: service tzupdate successfully started
s6-rc: info: service legacy-cont-init successfully started
usermod: user 'homebridge' does not exist
usermod: user 'homebridge' does not exist
s6-rc: warning: unable to start service setup: command exited 6
```

### Host Operating System

Raspberry Pi OS 11 - Bullseye

### Host Architecture

armv7l
