### ISSUE TITLE
Update node.js from 16.16.0 to 16.17.0?

### ISSUE THREAD

**Issue by Ronneke** [oznu/docker-homebridge#467]
### Current Situation

2 plugins report they need an update, a prerequisite is node.js version 16.17.0 i.s.o. 16.16.0.
When I issue the commands 
```
docker-compose pull
docker-compose up -d
```
I get the message node.js is up-to-date; but actually it is still version 16.16.0.
Any idea how to upgrade to 16.17.0?

### Docker Config

```yml
version: '2'
services:
  homebridge:
    image: oznu/homebridge:ubuntu
    container_name: homebridge
    restart: always
    network_mode: host
    environment:
      - TZ=Australia/Sydney
      - PGID=1000
      - PUID=1000
      - HOMEBRIDGE_CONFIG_UI=1
      - HOMEBRIDGE_CONFIG_UI_PORT=8581
    volumes:
      - ./homebridge:/homebridge
```

### Host Operating System

Raspberry Pi OS - Latest

### Host Architecture

armv7l
