### ISSUE TITLE
[Homebridge UI] Failed login attempt

### ISSUE THREAD

**Issue by mpuff** [oznu/docker-homebridge#469]
### Describe The Bug

<img width="1045" alt="Bildschirmfoto 2022-09-12 um 20 24 42" src="https://user-images.githubusercontent.com/13885599/189728445-e78ed06d-c240-4ec2-a38b-e03557446201.png">

### Docker Config

```yml
homebridge_home:
    container_name: homebridge_home
    image: oznu/homebridge
    restart: unless-stopped
    environment:
      - TZ=Europe/Vienna
      - HOMEBRIDGE_CONFIG_UI_PORT=8581
      - DSM_HOSTNAME=synology
    volumes:
      - /volume1/docker/homebridge_home:/homebridge
    network_mode: host
```

### Logs

```text
Failed login attempt
[9/12/2022, 8:26:22 PM] [Homebridge UI] If you've forgotten your password you can reset to the default of admin/admin by deleting the "auth.json" file (/var/lib/homebridge/auth.json) and then restarting Homebridge.
```

### Host Operating System

Synology DSM 7

### Host Architecture

x86_64 / amd64
