### ISSUE TITLE
Multi instance installation

### ISSUE THREAD

**Issue by miege2k** [oznu/docker-homebridge#470]
### Current Situation

I live in a building with several flats. I have a homebridge instance for my flat. my sister use home-app for his flat whitout homebridge. I need to share some devices to her and to my home-app. My solution was a second homebridge instance to share devices in a second building in the home-app. 

- When there is a other solution, please tell me.

If not can you tell me how I can start a second homebridge. 
- Can you give me the avahi.service for Homebridge because I run a avahi for samba.

- or the dockerfile how to run a second homebridge in docker.

Thanks for your help.

### Docker Config

```yml
version: '2'

services:
  homebridge:
    image: oznu/homebridge:2021-12-19
    restart: unless-stopped
    network_mode: host
    volumes:
      - /home/${USER}/data/home/homebridge/config:/homebridge
    environment:
      - PGID=1000
      - PUID=1000
      - HOMEBRIDGE_CONFIG_UI=1
      - HOMEBRIDGE_CONFIG_UI_PORT=8080
      - TZ=Europe/Berlin
    ports:
      - "8090:8080"
```

### Logs

```text
not interesting on this place
```

### Host Operating System

Ubuntu / Debian (or a variant)

### Host Architecture

x86_64 / amd64
