### ISSUE TITLE
Does this actually install homebridge-ui? 

### ISSUE THREAD

**Issue by rosshettel** [oznu/docker-homebridge#475]
### Current Situation

New user here, a little confused by the documentation and what I'm seeing.

[Following these instructions](https://github.com/homebridge/homebridge/wiki/Install-Homebridge-on-Docker#step-2-create-docker-compose-manifest) but they seem to be out of date, the `HOMEBRIDGE_CONFIG_UI_PORT` is apparently [no longer being used](https://github.com/oznu/docker-homebridge/issues/440).

That issue says you can configure the UI port via config.json directly. Ok, so my config.json looks like this:
```
{
    "bridge": {
        "name": "Homebridge",
        "username": "CC:22:3D:E3:CE:30",
        "port": 51826,
        "pin": "031-45-154"
    },

    "description": "This is an example configuration file. You can use this as a template for creating your own configuration file containing devices you actually own.",

    "accessories": [
    ],

    "platforms": [
    ]
}
```

Looking at [an example of the homebridge-ui config](https://github.com/oznu/homebridge-config-ui-x/blob/master/screenshots/homebridge-config-ui-x-config.png?2020-01-07) it seems `platforms` should not be empty? 

Regardless I'm not able to access the UI at all on any port, and indeed querying for services listening to the default port reports no results via `lsof -i :8581`

### Docker Config

```yml
homebridge:
        image: oznu/homebridge
        container_name: homebridge
        restart: unless-stopped
        network_mode: host
        environment:
            - TZ=${TZ}
        volumes:
            - /srv/homebridge:/homebridge
```

### Host Operating System

Ubuntu / Debian (or a variant)

### Host Architecture

x86_64 / amd64
