### ISSUE TITLE
Docker Startup Cannot Create symlink '../homebridge/bin/homebridge' -> '/homebridge/node_modules/.bin/homebridge'

### ISSUE THREAD

**Issue by grifonas** [oznu/docker-homebridge#480]
### Current Situation

I am trying to run Homebridge in my K8S cluster running on a Raspberry Pi 4. 
My K8S manifest is based on the docker-compose provided in the repo README. I am mounting a hostpath volume  into the /homebridge folder, as instructed in the readme. 
My docker image version is `latest` (as of 26.11.2022).

It looks like the startup script's having permission errors setting up the required symlinks (see the logs). This of course results in the UI error `[Homebridge UI] Unable To Find Homebridge Installation - see https://homebridge.io/w/JJSgZ for help.`.
I tried passing the `PGID` and `PUID` variables (setting the values to those of the folder owner on the host) however that resulted in the same error. 

Is there anything you can spot that I am missing?

Thank you!

### Docker Config

```yml
version: '2'
services:
  homebridge:
    image: oznu/homebridge:latest
    restart: always
    network_mode: host
    volumes:
      - ./volumes/homebridge:/homebridge
    logging:
      driver: json-file
      options:
        max-size: "10mb"
        max-file: "1"
```

### Logs

```text
[11/26/2022, 3:42:34 PM] [HB Supervisor] EPERM: operation not permitted, chown '/var/lib/homebridge/config.json'
npm ERR! code EPERM
npm ERR! syscall symlink
npm ERR! path ../homebridge/bin/homebridge
npm ERR! dest /homebridge/node_modules/.bin/homebridge
npm ERR! errno -1
npm ERR! Error: EPERM: operation not permitted, symlink '../homebridge/bin/homebridge' -> '/homebridge/node_modules/.bin/homebridge'
npm ERR!  [Error: EPERM: operation not permitted, symlink '../homebridge/bin/homebridge' -> '/homebridge/node_modules/.bin/homebridge'] {
npm ERR!   errno: -1,
npm ERR!   code: 'EPERM',
npm ERR!   syscall: 'symlink',
npm ERR!   path: '../homebridge/bin/homebridge',
npm ERR!   dest: '/homebridge/node_modules/.bin/homebridge'
npm ERR! }
npm ERR!
npm ERR! The operation was rejected by your operating system.
npm ERR! It is likely you do not have the permissions to access this file as the current user
npm ERR!
npm ERR! If you believe this might be a permissions issue, please double-check the
npm ERR! permissions of the file and its containing directories, or try running
npm ERR! the command again as root/Administrator.
```
```


### Host Operating System

Raspberry Pi OS 11 - Bullseye

### Host Architecture

armv7l
