### ISSUE TITLE
hostname 

### ISSUE THREAD

**Issue by antonlamers** [oznu/docker-homebridge#484]
### Current Situation

![image](https://user-images.githubusercontent.com/61295536/205433797-22d65b73-b860-4808-b6d3-c3da37323520.png)

### Docker Config

```yml
Hi
I have now this yml disable network mode and add ports. Did i this good or must is delete the - HOMEBRIDGE_CONFIG_UI_PORT=8581 row?

 # Homebridge
  homebridge:
    image: oznu/homebridge:raspberry-pi
    restart: unless-stopped
    # network_mode: host
    volumes:
      - ./volumes/homebridge:/homebridge
    environment:
      - PGID=1000
      - PUID=1000
      - HOMEBRIDGE_CONFIG_UI=1
      - HOMEBRIDGE_CONFIG_UI_PORT=8581
    ports:
    - 8581:8581

first i had this but for the hue bridge i must enter the current ip adres and after a reboot it was different. Is my edited file okay now can i use the hostname "deconz" within the hue bridge plugin
 # Homebridge
  homebridge:
    image: oznu/homebridge:raspberry-pi
    restart: unless-stopped
    # network_mode: host
    volumes:
      - ./volumes/homebridge:/homebridge
    environment:
      - PGID=1000
      - PUID=1000
      - HOMEBRIDGE_CONFIG_UI=1
      - HOMEBRIDGE_CONFIG_UI_PORT=8581
 # Deconz
  deconz:
    container_name: deconz
    image: deconzcommunity/deconz
    restart: unless-stopped
    privileged: true                             # This is important! Without it, the deCONZ image won't be able to connect to Conbee II.
    ports:
    - "8082:80"
    - "9443:443"
    - "5901:5900"
    - "6080:6080"
    volumes:
    - /etc/localtime:/etc/localtime:ro
    - ./volumes/deconz/:/opt/deCONZ
    devices:
    - /dev/ttyACM1                               # This is the USB device that Conbee II is running on.
    environment:
    - DECONZ_DEVICE=/dev/ttyACM1                 # This is the USB device that Conbee II is running on.
    - DECONZ_WEB_PORT=80
    - DECONZ_WS_PORT=443
    - DECONZ_VNC_MODE=1 
    - DECONZ_VNC_PASSWORD=changeme
    - DECONZ_VNC_PORT=5900
    - DECONZ_NOVNC_PORT=6080
    - DEBUG_INFO=1
    - DEBUG_APS=0
    - DEBUG_ZCL=0
    - DEBUG_ZDP=0
    - DEBUG_OTA=0
    - TZ=Europe/Amsterdam
```

### Host Operating System

Raspberry Pi OS 11 - Bullseye

### Host Architecture

aarch64 / arm64
