### ISSUE TITLE
Container restarting

### ISSUE THREAD

**Issue by BlackDiceagain** [oznu/docker-homebridge#486]
### Current Situation

hi the container on my raspberry keeps restarting. the latest software is on it. "Restarting (111)" I get as a message. What can I do?

### Docker Config

```yml
version: '2'
services:
  homebridge:
    image: oznu/homebridge:latest
    restart: always
    network_mode: host
    volumes:
      - ./config:/homebridge
    environment:
      - PGID=1000
      - PUID=1000
      - HOMEBRIDGE_CONFIG_UI=1
      - HOMEBRIDGE_CONFIG_UI_PORT=8080
```

### Host Operating System

Raspberry Pi OS - Latest

### Host Architecture

x86_64 / amd64
