### ISSUE TITLE
Portainer on Raspberrypi pulling ancient HB version

### ISSUE THREAD

**Issue by DerekSeaman** [oznu/docker-homebridge#496]
### Current Situation

I'm using Portainer on a RPi 4, and it's pulling an ancient version of HB. Specifically, HB 1.4.1 and Node.js v16.15. 

### Docker Config

```yml
version: '2'
services:
  homebridge:
    image: oznu/homebridge:raspberry-pi
    container_name: homebridge
    restart: always
    network_mode: host
    environment:
      - TZ=America/Los_Angeles
      - PGID=1000
      - PUID=1000
      - HOMEBRIDGE_CONFIG_UI=1
      - HOMEBRIDGE_CONFIG_UI_PORT=8581
    volumes:
      - ./homebridge:/homebridge
```

### Host Operating System

Raspberry Pi OS - Latest

### Host Architecture

aarch64 / arm64
