### ISSUE TITLE
Docker Compose network_mode = host does not open ports

### ISSUE THREAD

**Issue by mazshar** [oznu/docker-homebridge#502]
### Current Situation

I'm running an Ubuntu 22.04 LTS server with various docker containers using docker-compose. When I set `network_mode=host` and check with `docker ps` there are no open ports. However if I change the network mode to bridge and expose the ports, they appear.

```
CONTAINER ID   IMAGE                               COMMAND                  CREATED          STATUS                          PORTS                                                                                                                                                                                                                                                                                                                                                                                                NAMES
6c7d7ff2eab7   oznu/homebridge:2022-11-14          "/init"                  57 seconds ago   Up 45 seconds                                                                                                                                                                                                                                                                                                                                                                                                                        homebridge
```

Docker version 23.0.1, build a5ee5b1
Docker Compose version v2.16.0



### Docker Config

```yml
homebridge:
    container_name: homebridge
    image: oznu/homebridge:2022-11-14
    restart: unless-stopped
    network_mode: host
    volumes:
      - /config/homebridge:/homebridge
    logging:
      driver: json-file
      options:
        max-size: "10mb"
        max-file: "1"
    environment:
      - PGID=1001
      - PUID=1001
      - HOMEBRIDGE_CONFIG_UI=1
      - HOMEBRIDGE_CONFIG_UI_PORT=8581
```


### Logs

_No response_

### Host Operating System

Ubuntu / Debian (or a variant)

### Host Architecture

x86_64 / amd64
