### ISSUE TITLE
Unable to remove a plugin

### ISSUE THREAD

**Issue by Staubgeborener** [oznu/docker-homebridge#523]
### Current Situation

I'm trying to remove the `homebridge-tuya-platform` plugin. If i simply click the red bin icon there is no "delete" button afterward but a "save" button. So i click "safe" and nothing happens, also when i restart the docker container. 
So i stopped the docker container removes the plugin in terminal like `sudo rm -r homebridge-tuya-platform` (and also removed the cachedAccessories like `rm cachedAccessories` just in case). After that i am starting the container and the plugin is still there. I check with `ls` in `node_modules` and also the plugin is reinstalled there. So there is some sort of mechanism which seems to check some files (?) and reinstalls the plugin again and again. 

If i remove the plugin in terminal while the container is running, i can see in the UI that the plugin is truly removed. After restarting the docker container, it appears again.

OS: Linux 5.9.16-1-MANJARO (Homebridge running docker container)

### Docker Config

```yml
{
    "bridge": {
        "name": "Homebridge EDDA",
        "username": "---",
        "port": 53174,
        "pin": ""---","
    },
    "accessories": [],
    "platforms": [
        {
            "name": "Config",
            "port": 8087,
            "auth": "form",
            "theme": "dark-mode",
            "tempUnits": "c",
            "lang": "de",
            "platform": "config"
        },
        {
            "name": "TplinkSmarthome",
            "addCustomCharacteristics": true,
            "switchModels": [
                "HS100"
            ],
            "deviceTypes": [
                "plug",
                "bulb"
            ],
            "platform": "TplinkSmarthome"
        },
        {
            "name": "Roborock",
            "platform": "Camera-ffmpeg",
            "_bridge": {
                "username": "---",
                "port": 40422
            },
            "videoConfig": {
                "source": "-loop 1 -i http://192.168.178.34:3000/api/map/image",
                "videoFilter": "pad='ih*16/9:ih:(ow-iw)/2:(oh-ih)/2',scale=1920:1080",
                "maxFPS": 5
            }
        },
        {
            "name": "Hue",
            "anyOn": true,
            "brightnessAdjustment": 10,
            "effects": true,
            "heartrate": 2,
            "hosts": [
                "192.168.178.34:9091"
            ],
            "lights": true,
            "linkButton": true,
            "nativeHomeKitLights": true,
            "nativeHomeKitSensors": true,
            "resource": true,
            "sensors": true,
            "users": {
                "": ""
            },
            "wallSwitch": true,
            "platform": "Hue"
        }
    ]
}
```

### Host Operating System

Other (specify in description)

### Host Architecture

x86_64 / amd64
