### ISSUE TITLE
Exposing port 8000

### ISSUE THREAD

**Issue by holocronology** [oznu/docker-homebridge#540]
### Current Situation

Docker-Homebridge appears to have co-opted port 8000 and exposes is when running.
There does not appear to be any notation about this in the documentation.
Is this intended and why?
Shouldn't think noted somewhere?

### Docker Config

```yml
version: '3'
services:
  homebridge:
    image: homebridge/homebridge:latest
    container_name: homebridge
    restart: always
    network_mode: host
    security_opt:
      - no-new-privileges:true
    ports:
      - 8581:8581
    environment:
      - PGID=xxxx
      - PUID=xxxx
      - HOMEBRIDGE_CONFIG_UI=1
      - HOMEBRIDGE_CONFIG_UI_PORT=8581
      - TZ=America/New_York
      - DSM_HOSTNAME=xxxx
    volumes:
      - /volume1/docker/homebridge:/homebridge
      # - /volume1/data/sites/static/cams:/cams
    healthcheck:
      test: curl --fail xxxx:8581 || exit 1
      interval: 60s
      retries: 5
      start_period: 300s
      timeout: 2s
```

### Host Operating System

Synology DSM 7

### Host Architecture

x86_64 / amd64
