### ISSUE TITLE
Homebridge keep restarting after update

### ISSUE THREAD

**Issue by JornDL** [oznu/docker-homebridge#544]
### Describe The Bug

After latest update the Homebridge keeps restarting.

It has been running fine for a couple of years.

### Docker Config

```yml
version: '3'
services:
  homebridge:
    image: homebridge/homebridge:latest
    container_name: homebridge
    restart: unless-stopped
    network_mode: host
    environment:
      - HOMEBRIDGE_CONFIG_UI_PORT=8581
      - TZ=Europe/Copenhagen

    volumes:
      - /home/jorn/homebridge:/homebridge
```

### Logs

```text
[1/3/2024, 8:23:08 AM] AssertionError [ERR_ASSERTION]: Cannot generate setupURI on an accessory that isn't published yet!
    at Bridge.Accessory.setupURI (/homebridge/node_modules/homebridge/node_modules/hap-nodejs/src/lib/Accessory.ts:994:11)
    at Server.setServerStatus (/homebridge/node_modules/homebridge/src/server.ts:155:45)
    at Server.teardown (/homebridge/node_modules/homebridge/src/server.ts:199:10)
    at signalHandler (/homebridge/node_modules/homebridge/src/cli.ts:93:12)
    at process.emit (node:events:517:28)
    at process.emit (/homebridge/node_modules/homebridge/node_modules/source-map-support/source-map-support.js:516:21)
```

### Host Operating System

Ubuntu / Debian (or a variant)

### Host Architecture

x86_64 / amd64
