### ISSUE TITLE
Lost configuration after container restart / host reboot

### ISSUE THREAD

**Issue by Tamas92** [oznu/docker-homebridge#551]
### Describe The Bug

I had a power outage and after my server rebooted I've got the default start screen for homebridge. Create user or restore from backup. I restored from backup. Rebooted the host and had the default screen again. If I stop then start the container I have the same issue.
I tried to create the new user to have a new config. Same issue after reboot/container restart. Always lose all the config.

![Screenshot 2024-02-11 at 19 17 22](https://github.com/homebridge/docker-homebridge/assets/63238832/1d60142e-a6ec-4e1e-909b-b1d030711ebd)

### Docker Config

```yml
version: '2'
services:
  homebridge:
    container_name: homebridge
    image: homebridge/homebridge:ubuntu
    restart: always
    network_mode: host
    volumes:
      - ./homebridge:/homebridge
      - ./cameraui:/var/lib/homebridge/camera.ui/recordings/
    logging:
      driver: json-file
      options:
        max-size: "10mb"
        max-file: "1"
```

### Host Operating System

Ubuntu / Debian (or a variant)

### Host Architecture

x86_64 / amd64
