### ISSUE TITLE
Cannot connect to ui

### ISSUE THREAD

**Issue by Masterpc96** [oznu/docker-homebridge#555]
### Current Situation

I made a container I can add homebridge to home but I cannot open ui on port 8581
Dell Optiplex with Debian 12

### Docker Config

```yml
version: '3'
services:
  homebridge:
    image: homebridge/homebridge:latest
    container_name: homebridge
    restart: always
    network_mode: host
    logging:
      driver: json-file
      options:
        max-size: '10m'
        max-file: '1'
    healthcheck:
      test: curl --fail localhost:8581 || exit 1
      interval: 60s
      retries: 5
      start_period: 300s
      timeout: 2s
    environment:
      - PGID=1000
      - PUID=1000
      - HOMEBRIDGE_CONFIG_UI=1
      - HOMEBRIDGE_CONFIG_UI_PORT=8581
    volumes:
      - homebridge:/homebridge
volumes:
  homebridge:
```

### Host Operating System

Debian 12

### Host Architecture

x86_64 / amd64
