### ISSUE TITLE
dbus and other pids are deleted off the host

### ISSUE THREAD

**Issue by koush** [oznu/docker-homebridge#557]
### Describe The Bug

This is the setup guide for avahi:

https://github.com/homebridge/homebridge/wiki/mDNS-Options#avahi-linux-and-docker

```yaml
    security_opt:
      - apparmor:unconfined
    volumes:
      - /var/run/dbus:/var/run/dbus
      - /var/run/avahi-daemon/socket:/var/run/avahi-daemon/socket
      - ...
```

The avahi startup script will delete the running pids in the container: https://github.com/homebridge/docker-homebridge/blob/eff9b94690dbac328929d43296af033bc561a303/rootfs/etc/s6-overlay/scripts/setup.sh#L7

```sh
# delete existing pids if they exist
[ -e /var/run/dbus.pid ] && rm -f /var/run/dbus.pid
[ -e /var/run/dbus/pid ] && rm -f /var/run/dbus/pid 
[ -e /run/dbus/pid ] && rm -f /run/dbus/pid
```

Specifically this pid is within the rw volume on the host machine: `/var/run/dbus/pid`

Seems to be a bug.

### Docker Config

```yml
N/A
```

### Host Operating System

Ubuntu / Debian (or a variant)

### Host Architecture

x86_64 / amd64
