### ISSUE TITLE
Config is not persistent

### ISSUE THREAD

**Issue by 3DJupp** [oznu/docker-homebridge#586]
### Current Situation

Upon stack updates (using portainer) the homebridge config is lost.
I tried to set persistent locations for the directories:

- /homebridge
- /var/lib/homebridge
- /opt/homebridge
- /home/homebridge

### Docker Config

```yml
homebridge:
    image: homebridge/homebridge:latest
    hostname: "homebridge"
    volumes:
      - hb_data:/homebridge
      - hb_lib:/var/lib/homebridge
      - hb_opt:/opt/homebridge
      - hb_home:/home/homebridge
    environment:
      - PUID=$UID_SMB
      - PGID=$GID_SMB
      - HOMEBRIDGE_CONFIG_UI_PORT=$hb_http
      - HOMEBRIDGE_CONFIG_UI=1
    networks:
      #bridge: # disabled, the container is not working with bridge IP
      net_public:
        ipv4_address: $hb_IP # the exposed IPv4 of the homebridge container
    logging:
      driver: json-file
      options:
        max-size: "10mb"
        max-file: "1"
    restart: unless-stopped
    healthcheck:
      test: ["CMD-SHELL", "curl -s -f http://localhost:${hb_http}/ || exit 1"] #-s/--silent: Silent mode;-f/--fail: Fail silently
      interval: 30s
      timeout: 5s
      retries: 3
      start_period: 30s
    depends_on:
      openhab:
        condition: service_healthy
networks:
  net_public: # externally created network (external IP can be assigned)
    external: true
  bridge: # internal bridge networtk
    external: false
```

### Logs

```text
s6-rc: info: service s6rc-oneshot-runner: starting
s6-rc: info: service s6rc-oneshot-runner successfully started
s6-rc: info: service fix-attrs: starting
s6-rc: info: service tzupdate: starting
s6-rc: info: service setup: starting
s6-rc: info: service credits: starting

    Thank you for using the homebridge/homebridge docker image!

  If you find this project useful please STAR it on GitHub:

         https://github.com/homebridge/docker-homebridge

                Or donate to the project:

            https://github.com/sponsors/oznu
                  https://paypal.me/oznu

s6-rc: info: service credits successfully started
s6-rc: info: service fix-attrs successfully started
s6-rc: info: service legacy-cont-init: starting
s6-rc: info: service tzupdate successfully started
s6-rc: info: service legacy-cont-init successfully started
rm: cannot remove '/var/lib/homebridge': Device or resource busy
Installing Homebridge and user plugins, please wait...

up to date in 1s
s6-rc: info: service setup successfully started
s6-rc: info: service userdata: starting
s6-rc: info: service dbus: starting
s6-rc: info: service dbus successfully started
s6-rc: info: service avahi: starting
Executing user startup script /homebridge/startup.sh
Starting dbus-daemon
s6-rc: info: service avahi successfully started
s6-rc: info: service userdata successfully started
s6-rc: info: service homebridge: starting
s6-rc: info: service homebridge successfully started
s6-rc: info: service homebridge-log: starting
s6-rc: info: service homebridge-log successfully started
s6-rc: info: service legacy-services: starting
Re-installing homebridge...
s6-rc: info: service legacy-services successfully started
Starting Avahi daemon
Found user 'avahi' (UID 101) and group 'avahi' (GID 103).
Successfully dropped root privileges.
avahi-daemon 0.8 starting up.
No service file found in /etc/avahi/services.
Joining mDNS multicast group on interface eth0.IPv4 with address 172.16.0.123.
New relevant interface eth0.IPv4 for mDNS.
Joining mDNS multicast group on interface lo.IPv4 with address 127.0.0.1.
New relevant interface lo.IPv4 for mDNS.
Network interface enumeration completed.
Registering new address record for 172.17.0.103 on eth0.IPv4.
Registering new address record for ::1 on lo.*.
Registering new address record for 127.0.0.1 on lo.IPv4.
Server startup complete. Host name is homebridge.local. Local service cookie is 177875154.

added 112 packages in 3s
[1/17/2025, 12:26:40 PM] [HB Supervisor] Homebridge storage path: /var/lib/homebridge.
[1/17/2025, 12:26:40 PM] [HB Supervisor] Homebridge config path: /var/lib/homebridge/config.json.
[1/17/2025, 12:26:40 PM] [HB Supervisor] Logging to /var/lib/homebridge/homebridge.log.
```

### Host Operating System

Ubuntu / Debian (or a variant)

### Host Architecture

x86_64 / amd64
