### ISSUE TITLE
PUID/PGID not honoured, docker runs as root

### ISSUE THREAD

**Issue by tnowak** [oznu/docker-homebridge#597]
### Describe The Bug

Hi, I'm using the compose file below, but docker seems to be running as root anyway. Why is that? Is this a bug?

<img width="939" alt="Image" src="https://github.com/user-attachments/assets/1ebd70ce-c79b-4049-b774-fdb3100729b0" />

OS: dietpi latest (Bookworm)

### Docker Config

```yml
version: '3'
services:
  homebridge:
    container_name: homebridge
    image: homebridge/homebridge:latest
    network_mode: host
    volumes:
      - /opt/homebridge:/homebridge
    logging:
      driver: json-file
      options:
        max-size: "10mb"
        max-file: "1"
    environment:
      - TZ=Europe/Warsaw
      - PUID=1001
      - PGID=1001
    restart: always
```

### Logs

```text

```

### Host Operating System

Other (specify in description)

### Host Architecture

x86_64 / amd64
