### ISSUE TITLE
Help with YAML

### ISSUE THREAD

**Issue by idle0095** [oznu/docker-homebridge#598]
### Current Situation

I cant seem to get the YAML to install.  I entered everything I believe is correct.  Please any help.

### Docker Config

```yml
networks:
  homebridge_net:
    driver: macvlan
    driver_opts:
      parent: eno1
    ipam:
      config:
        - gateway: 192.168.1.214
          subnet: 192.168.1.214/24
services:
  homebridge:
    container_name: homebridge
    deploy:
      resources:
        limits:
          cpus: '2.5'
          memory: 3072M
    image: homebridge/homebridge:latest
    networks:
      homebridge_net:
        ipv4_address: 192.168.1.1
    restart: unless-stopped
    volumes:
      - /mnt/Pool/homebridge
```

### Logs

```text

```

### Host Operating System

Raspberry Pi OS - Latest

### Host Architecture

x86_64 / amd64
