### ISSUE TITLE
Cannot access services outside Truenas Scale container

### ISSUE THREAD

**Issue by heggink** [oznu/docker-homebridge#602]
### Current Situation

The container starts fine but is not able to connect to my mosquitto broker running on the same host (192.168.1.109). From the container, I can ping the outside world. I use the following network settings:

    ipam:
      config:
        - gateway: 192.168.1.1 # gateway of your LAN
          subnet: 192.168.1.0/24 # subnet of your LAN

      homebridge_net:
        ipv4_address: 192.168.1.25 # homebridge IPv4

Any idea what I am doing wrong? My router gives out IP addresses as of 192.168.1.50...

Running Truenas Scale 25.04.0

Many thanks!

### Docker Config

```yml
networks:
  homebridge_net:
    driver: macvlan
    driver_opts:
      parent: enp6s0
    ipam:
      config:
        - gateway: 192.168.1.1
          subnet: 192.168.1.0/24
services:
  homebridge:
    container_name: homebridge
    deploy:
      resources:
        limits:
          cpus: '2.5'
          memory: 3072M
    image: homebridge/homebridge:latest
    networks:
      homebridge_net: Null
    restart: unless-stopped
    volumes:
      - /mnt/Main/Dockers/homebridge:/homebridge
```

### Logs

```text

```

### Host Operating System

Other (specify in description)

### Host Architecture

x86_64 / amd64
